// English for features/accounts (merged by i18n/index.ts). Keys are the Chinese source strings; {} = interpolation.
export const en: Record<string, string> = {
  // dialog
  "所有帳戶": "Accounts",
  "帳戶類別": "Classes",
  "類別": "Class",
  // account list
  "{} 個帳戶": "{} account|{} accounts",
  "{} 個帳戶使用": "{} account uses it|{} accounts use it",
  "已封存 {} 個帳戶": "{} archived account|{} archived accounts",
  "記下第一筆餘額": "Record first balances",
  "完成": "Done",
  "還沒有帳戶": "No accounts yet",
  "銀行、證券戶、房子、車、房貸,各建一個帳戶。之後每次只要更新餘額。": "Create one account each for your bank, brokerage, home, car and mortgage. After that you only update balances.",
  "尚未記錄": "Not recorded yet",
  "把「{}」往上移": "Move “{}” up",
  "把「{}」往下移": "Move “{}” down",
  // account form
  "名稱": "Name",
  "例如:玉山活存": "e.g. Everyday checking",
  "幣別": "Currency",
  "已經有餘額紀錄,幣別不能改": "Balances are recorded, so the currency can't change",
  "三個英文字母,例如 TWD、USD": "Three letters, e.g. TWD, USD",
  "備註": "Note",
  "帳號末四碼、用途…": "Last four digits, purpose…",
  "請選一個類別": "Pick a class",
  "儲存": "Save",
  "新增": "Add",
  "取消": "Cancel",
  "封存": "Archive",
  "刪除帳戶": "Delete account",
  "永久刪除": "Delete permanently",
  "已新增「{}」,到「記一筆」填第一筆餘額": "Added “{}”. Use Record to enter its first balance.",
  "已更新「{}」": "Updated “{}”",
  "封存「{}」?": "Archive “{}”?",
  "封存後會收進資產負債表下方的「已封存」,歷史紀錄仍保留在趨勢圖裡。": "It moves to “Archived” under the balance sheet; its history stays in the trend.",
  "目前餘額還有 {} {},封存後仍會算進淨資產。帳戶已結清的話,先記一筆 0 再封存。": "It still holds {} {}, which keeps counting toward net worth. If the account is closed, record a 0 first, then archive.",
  "已封存「{}」": "Archived “{}”",
  "已取消封存「{}」": "Unarchived “{}”",
  "刪除「{}」?": "Delete “{}”?",
  "會一起刪掉它的 {} 筆餘額紀錄,淨資產和趨勢都會重算,無法復原。只是不想再看到的話,用「封存」就好。": "This also deletes its {} balance record, and net worth and trends are recalculated. It can't be undone. To just hide it, use Archive.|This also deletes its {} balance records, and net worth and trends are recalculated. It can't be undone. To just hide it, use Archive.",
  "已刪除「{}」": "Deleted “{}”",
  // history
  "歷史紀錄": "History",
  "{} 筆 · 改完按 Enter 或離開該列就會儲存": "{} record · saves on Enter or when you leave the row|{} records · each saves on Enter or when you leave its row",
  "儲存中": "Saving",
  "移到最上面": "Move to top",
  "移到最下面": "Move to bottom",
  "移動「{}」": "Move “{}”",
  "還沒有紀錄。到「記一筆」填第一筆餘額。": "No records yet. Use Record to enter the first balance.",
  "日期": "Date",
  "餘額({})": "Balance ({})",
  "匯率": "Rate",
  "價值({})": "Value ({})",
  "動作": "Actions",
  "顯示全部 {} 筆": "Show all {} record|Show all {} records",
  "只顯示最近的": "Show recent only",
  "{} 餘額": "{} balance",
  "{} 匯率": "{} rate",
  "刪除這列": "Delete row",
  "刪除 {} 這筆": "Delete the {} record",
  "已更新 {} 的紀錄": "Updated the {} record",
  "刪除 {} 這筆紀錄?": "Delete the {} record?",
  "趨勢圖會改用前一筆餘額接續。": "The trend carries the previous balance forward instead.",
  "刪除": "Delete",
  // kinds
  "類別決定帳戶的顏色,以及在資產負債表裡算哪一層;流動性選「負債」的類別會從淨資產扣掉。": "A class sets an account's color and its tier on the balance sheet. Classes with liquidity “Liabilities” are subtracted from net worth.",
  "新增類別": "Add class",
  "流動資產": "Liquid assets",
  "投資資產": "Investments",
  "自用資產": "Personal-use assets",
  "{} 的顏色": "{} color",
  "{} 的名稱": "{} name",
  "{} 的流動性": "{} liquidity",
  "刪除類別": "Delete class",
  "刪除類別「{}」": "Delete class “{}”",
  "刪除類別「{}」?": "Delete class “{}”?",
  "沒有帳戶使用這個類別,刪除後可以再新增。": "No account uses this class. You can add it again later.",
  "已刪除類別「{}」": "Deleted class “{}”",
  "還有帳戶使用,不能刪除": "In use by accounts, can't delete",
  "不能刪除「{}」": "Can't delete “{}”",
  "還有 {} 個帳戶使用這個類別,請先改到別的類別": "{} account still uses this class. Move it to another class first.|{} accounts still use this class. Move them to another class first.",
  // kind form
  "例如:保險、退休金": "e.g. Insurance, Pension",
  "顏色": "Color",
  "流動性": "Liquidity",
  "「負債」會從淨資產扣掉": "“Liabilities” are subtracted from net worth",
  "已新增類別「{}」": "Added class “{}”",
  "把「{}」改成負債?": "Make “{}” a liability?",
  "把「{}」改成資產?": "Make “{}” an asset?",
  "這個類別的 {} 個帳戶會從淨資產扣掉,所有歷史的淨資產都會重算。": "Its {} account will be subtracted from net worth, and every past net worth is recalculated.|Its {} accounts will be subtracted from net worth, and every past net worth is recalculated.",
  "這個類別的 {} 個帳戶會算進資產,所有歷史的淨資產都會重算。": "Its {} account will count as an asset, and every past net worth is recalculated.|Its {} accounts will count as assets, and every past net worth is recalculated.",
  "確定修改": "Change it",
  // server messages for these routes (missing from i18n/en.ts)
  "類別名稱必填,最多 30 字": "Class name is required, up to 30 characters",
  "代號要是小寫英文開頭,2–32 個小寫英文、數字或底線": "Key must start with a lowercase letter: 2–32 lowercase letters, digits or underscores",
  "這個代號已經存在": "That key already exists",
  "顏色格式要是 #rrggbb": "Color must be #rrggbb",
  "流動性要是 liquid、invest、fixed 或 liability": "Liquidity must be liquid, invest, fixed or liability",
  "找不到這個類別": "Class not found",
  "備註太長": "Note is too long",
  "格式不正確": "Invalid format",
  "ids 格式不正確": "Invalid ids",
  "ids 不能重複": "ids can't repeat",
  "它的 {} 筆紀錄會改從淨資產扣掉,所有歷史的淨資產都會重算。": "Its {} record will now be subtracted from net worth, and every past net worth is recalculated.|Its {} records will now be subtracted from net worth, and every past net worth is recalculated.",
  "它的 {} 筆紀錄會改算進資產,所有歷史的淨資產都會重算。": "Its {} record will now count as an asset, and every past net worth is recalculated.|Its {} records will now count as an asset, and every past net worth is recalculated.",
  "已經有同名的帳戶": "An account with that name already exists",
}
