export const en: Record<string, string> = {
  "大事記": "Milestones",
  "買房、換工作、年終這類轉折,會畫在趨勢圖上。": "Turning points like buying a home, a new job or a year-end bonus are drawn on the trend.",
  "新增大事": "Add milestone",
  "編輯大事": "Edit milestone",
  "還沒有大事": "No milestones yet",
  "像「買房」這種會讓曲線轉彎的事,記下來會在趨勢圖上畫成一條參考線,回頭看更清楚。":
    "Record things that bend the curve, like buying a home. Each one shows up as a reference line on the trend, so looking back is easier.",
  "大事記,由新到舊": "Milestones, newest first",
  "當時淨資產": "Net worth then",
  "編輯": "Edit",
  "刪除": "Delete",
  "編輯 {}": "Edit {}",
  "刪除 {}": "Delete {}",
  "刪除這件大事?": "Delete this milestone?",
  "已刪除「{}」": "Deleted “{}”",
  "取消": "Cancel",
  "新增": "Add",
  "儲存": "Save",
  "已更新": "Updated",
  "已加到大事記": "Added to milestones",
  "會在趨勢圖上畫一條虛線,方便對照淨資產的轉折。": "Drawn as a dashed line on the trend, so you can match it against turns in net worth.",
  "日期": "Date",
  "事件": "Milestone",
  "例:買房、換工作、年終入帳": "e.g. bought a home, new job, year-end bonus",
  "請選日期": "Pick a date",
  "請輸入事件名稱": "Enter a name for the milestone",
}
