// English for features/settings. Keys are the Chinese source strings; "{}" marks a T`` interpolation.
export const en: Record<string, string> = {
  // drawer
  "帳本": "Ledger",
  "帳本叫什麼、用哪個幣別當基準。": "Name this ledger and pick its base currency.",
  "顯示": "Display",
  "首頁區塊": "Dashboard sections",
  "調整順序或隱藏;最上方的淨資產總覽固定顯示。": "Reorder or hide sections. The net-worth overview always stays on top.",
  "匯入與匯出": "Import & export",
  // ledger
  "帳本名稱": "Ledger name",
  "副標": "Subtitle",
  "基準幣別": "Base currency",
  "已經有餘額紀錄,基準幣別不能再改。": "Balances exist, so the base currency is locked.",
  "所有金額都換算成這個幣別。開始記帳後就不能改。": "Every amount converts to this currency. It locks once you record a balance.",
  "儲存": "Save",
  "已儲存設定": "Settings saved",
  // display
  "金額單位": "Amount unit",
  "萬": "10K (萬)",
  "完整": "Full",
  "例:{}": "e.g. {}",
  "語言": "Language",
  "外觀": "Appearance",
  "淺色": "Light",
  "深色": "Dark",
  "跟隨系統": "System",
  "語言和外觀只存在這台裝置;金額單位存在帳本裡。": "Language and appearance are saved on this device; the amount unit is saved with the ledger.",
  // layout
  "首頁區塊順序": "Dashboard section order",
  "{} 上移": "Move {} up",
  "{} 下移": "Move {} down",
  "顯示 {}": "Show {}",
  "恢復預設": "Reset to default",
  // export
  "試算表 CSV": "Spreadsheet CSV",
  "帳戶一列、日期一欄,附各類小計與淨資產。Excel、Numbers 直接開。": "One row per account, one column per date, with class subtotals and net worth. Opens in Excel or Numbers.",
  "完整備份 .db": "Full backup .db",
  "包含帳戶、每筆餘額、匯率、大事、貸款。要還原時把它換成 wealth.db。": "Accounts, every balance, rates, milestones and loans. To restore, swap it in as wealth.db.",
  "伺服器每天自動備份一份到 backups/,保留最近 30 天。": "The server also backs up to backups/ every day and keeps the last 30 days.",
  "資料存在 Cloudflare D1,內建 30 天內任一時間點還原(Time Travel)。": "Data lives in Cloudflare D1, which can restore any point in the last 30 days (Time Travel).",
  "下載": "Download",
  // import
  "匯入餘額 CSV": "Import balances from CSV",
  "欄位:date,account,amount,fx(fx 可省略,會自動查當天匯率)。帳戶名稱要完全相同。": "Columns: date,account,amount,fx (fx is optional and looked up for that day). Account names must match exactly.",
  "下載範本": "Download template",
  "選擇 .csv 檔": "Choose a .csv file",
  "帳戶名稱": "Account name",
  "關閉": "Close",
  "選好檔案後會先預覽,確認沒問題再匯入。": "Pick a file to preview it first; nothing is imported until you confirm.",
  "匯入預覽": "Import preview",
  "日期": "Date",
  "帳戶": "Account",
  "金額": "Amount",
  "匯率": "Rate",
  "自動": "Auto",
  "共 {} 筆": "{} row|{} rows",
  "覆蓋 {} 筆": "{} overwrite|{} overwrites",
  "只顯示前 {} 筆。": "Showing the first {} rows.",
  "找不到這些帳戶": "These accounts don't exist",
  "先在「帳戶與類別」新增,或把 CSV 裡的名稱改成跟現有帳戶一樣。": "Add them under Accounts & classes first, or rename them in the CSV to match existing accounts.",
  "第 {} 列的日期(YYYY-MM-DD)、金額或匯率不正確。": "Row {} has an invalid date (YYYY-MM-DD), amount or rate.",
  "匯入 {} 筆": "Import {} row|Import {} rows",
  "覆蓋既有餘額?": "Overwrite existing balances?",
  "有 {} 筆的帳戶在同一天已經有餘額,匯入後會被 CSV 的數字取代。": "{} row hits an account that already has a balance on that date. The CSV value will replace it.|{} rows hit an account that already has a balance on that date. The CSV values will replace them.",
  "匯入並覆蓋": "Import and overwrite",
  "取消": "Cancel",
  "已匯入 {} 筆餘額": "Imported {} balance|Imported {} balances",
  // import errors (client check and the same messages from POST /api/import)
  "檔案讀取失敗或超過 1 MB": "Couldn't read the file, or it's over 1 MB",
  "CSV 是空的或格式錯誤": "The CSV is empty or malformed",
  "第一列要是標題:date,account,amount,fx(fx 可省略)": "The first row must be the header date,account,amount,fx (fx optional)",
  "CSV 沒有資料列": "The CSV has no data rows",
  "一次最多匯入 {} 筆,請分批": "At most {} rows per import; split the file",
  "這個檔案用分號分隔,請改成逗號分隔的 CSV": "This file uses semicolons; save it as comma-separated CSV",
  "檔案不是 UTF-8 編碼,請在 Excel 另存成「CSV UTF-8」": "The file isn't UTF-8. In Excel, save it as “CSV UTF-8”",
  "第 {} 列格式錯誤": "Row {} is malformed",
  "第 {} 列的日期(YYYY-MM-DD)或帳戶名稱不正確": "Row {} has an invalid date (YYYY-MM-DD) or account name",
  "第 {} 列的金額不是數字": "Row {}: the amount isn't a number",
  "第 {} 列的匯率不正確": "Row {}: invalid rate",
  "找不到這些帳戶:{}": "These accounts don't exist: {}",
  "有好幾個帳戶叫這些名字,請先改成不同的名字:{}": "Several accounts share these names; rename them first: {}",
  "有 {} 組幣別和日期要查匯率,一次最多 {} 組,請在 CSV 填 fx 欄": "{} currency-and-date pairs need a rate lookup (at most {}). Fill in the fx column.",
  "查不到 {} 在 {} 的匯率,請在 CSV 填 fx": "Couldn't find the {} rate for {}. Fill in fx in the CSV.",
  "餘額明細 CSV": "Balances CSV",
  "每筆餘額一列(date,account,amount,fx),跟匯入的格式相同,可以直接匯回來。": "One row per balance (date,account,amount,fx), the same layout the import reads, so it re-imports as is.",
  "版面設定要是 4 KB 以內的 JSON": "Layout must be JSON under 4 KB",
  "清除": "Clear",
}
