// English for the balance sheet and the record dialog. Shell strings (記一筆, 新增帳戶, 負債…) live in i18n/en.ts.
export const en: Record<string, string> = {
  // balance sheet
  "淨資產 = 資產合計 − 負債。金額以 {} 計,點帳戶可編輯。": "Net worth = total assets − liabilities. Amounts in {}; click an account to edit it.",
  "資產": "Assets",
  "負債與淨資產": "Liabilities & net worth",
  "{} 個帳戶": "{} account|{} accounts",
  "{} 筆負債": "{} liability|{} liabilities",
  "流動資產": "Liquid assets",
  "投資資產": "Investments",
  "自用資產": "Personal-use assets",
  "佔資產": "Share of assets",
  "負債比": "Debt ratio",
  "資產合計": "Total assets",
  "負債與淨資產合計": "Liabilities + net worth",
  "= 資產合計": "= total assets",
  "淨資產": "Net worth",
  "淨資產(資不抵債)": "Net worth (underwater)",
  "還沒有資產帳戶。": "No asset accounts yet.",
  "沒有負債。": "No liabilities.",
  "顯示已封存({})": "Show archived ({})",
  "隱藏已封存": "Hide archived",
  "已封存": "Archived",
  "沒有使用中的帳戶": "No active accounts",
  "新增一個帳戶,或顯示已封存的帳戶。": "Add an account, or show archived ones.",
  "尚未記錄": "Not recorded yet",
  "編輯、看歷史紀錄": "Edit, see history",
  "較上次紀錄": "Change since the previous record",
  // record dialog
  "日期": "Date",
  "改有變動的帳戶就好,其他會沿用上一筆。按 Enter 跳下一個,也可以貼上一整欄數字。": "Only change what moved; the rest carries forward. Enter jumps to the next one, and you can paste a whole column of numbers.",
  "補記 {}:每列先帶入當天的餘額,只會存你改過的帳戶。": "Backfilling {}: each row starts at that day's balance, and only the rows you change are saved.",
  "{} 的淨資產": "Net worth on {}",
  "這天已有紀錄": "Already recorded this day",
  "覆蓋 {} 的紀錄?": "Overwrite the {} records?",
  "這些帳戶在 {} 已經有餘額,會改成這次填的數字:{}": "These accounts already have a balance on {}, which will be replaced: {}",
  "覆蓋": "Overwrite",
  "沿用上一筆": "Carry forward",
  "{} 餘額({})": "{} balance ({})",
  "{} 匯率 {}/{}": "{} rate {}/{}",
  "看不懂這個數字": "Not a number",
  "匯率要大於 0": "Rate must be above 0",
  "正在取得匯率": "Fetching rate",
  "上次 {}": "Last {}",
  "淨資產 {}": "Net worth {}",
  "{} 的匯率沒抓到:有舊紀錄的帳戶先沿用上一次的匯率,第一次記錄的請手動填匯率。": "Couldn't fetch the {} rate. Accounts with earlier records keep their last rate; for a first record, enter the rate by hand.",
  "變成": "becomes",
  "取消": "Cancel",
  "儲存 {} 筆": "Save {} change|Save {} changes",
  "沒有變動": "No changes",
  "已記錄 {}": "Recorded {}",
  "{} 個帳戶 · 淨資產 {}({})": "{} account · net worth {} ({})|{} accounts · net worth {} ({})",
  "放棄 {} 筆未儲存的餘額?": "Discard {} unsaved balance?|Discard {} unsaved balances?",
  "關掉後這次填的數字都不會保留。": "Closing now throws away the numbers you typed.",
  "放棄": "Discard",
  "繼續填": "Keep editing",
  "匯率": "Rate",
  "請填匯率": "Enter a rate",
}
