export const en: Record<string, string> = {
  // hero
  "淨資產": "Net worth",
  "目標 {}": "Goal {}",
  "目標 {} · {}": "Goal {} by {}",
  "已達成 {}": "{} reached",
  "已達標。": "Goal reached.",
  "照近一年的速度,{} 到。": "At the past year's pace, you get there {}.",
  "比目標早 {} 個月。": "{} months ahead of the date.",
  "比目標晚 {} 個月。": "{} months behind the date.",
  "近一年沒有成長,照這個速度不會達到。": "No growth over the past year, so this pace never gets there.",
  "再記一年,就能算出照這個速度何時達到。": "After a year of records, this shows when the current pace gets there.",
  "淨資產 · 截至 {}": "Net worth · as of {}",
  "尚無紀錄": "No records yet",
  "較上一筆紀錄({})": "since the previous record ({})",
  "{}的變動:": "{}, what moved:",
  "最大的帳戶:": "Biggest account move:",
  "平均每年 {}": "{} a year on average",
  "用上方的時間範圍或「自訂」日期縮放,或拖曳圖表下方滑桿的兩端": "Zoom with the time range or Custom dates above, or drag the handles under the chart",
  "資產流動性": "Liquidity",
  "隨時能動用的錢佔多少,一眼看清。": "How much of what you own you could actually spend.",
  "資產流動性:{}": "Liquidity: {}",
  "記下第一筆資產後,這裡會顯示流動性比例。": "Record your first asset to see how liquid you are.",
  "總資產": "Total assets",
  "負債比": "Debt ratio",
  // trend
  "3個月": "3M",
  "6個月": "6M",
  "1年": "1Y",
  "3年": "3Y",
  "5年": "5Y",
  "全部": "All",
  "時間範圍": "Time range",
  "每一次記錄的淨資產;虛線是你標記的大事。": "Net worth at every record; dashed lines are your milestones.",
  "自 {} 起": "Since {}",
  "近 {} 年": "Past {} yr",
  "近 {} 個月": "Past {} months",
  "淨資產趨勢折線圖,{} 筆紀錄,從 {} 的 {} 到 {} 的 {}": "Net worth trend line chart, {} records, from {} ({}) to {} ({})",
  "拖曳圖表下方滑桿的兩端(或用 Tab 選取後按方向鍵),放大一段期間": "Drag the handles under the chart (or Tab to one and use the arrow keys) to zoom into a period",
  "縮放範圍:{} 到 {}": "Zoom range: {} to {}",
  "{}主要變動": "Biggest moves, {}",
  "(淨資產 {})": "(net worth {})",
  "{} 個帳戶超過 90 天沒更新:{}": "{} account hasn't been updated in 90+ days: {}|{} accounts haven't been updated in 90+ days: {}",
  "更新餘額": "Update balances",
  "還原縮放": "Reset zoom",
  "再記一筆,就能畫出趨勢": "One more record and the trend appears",
  "還沒有任何紀錄": "No records yet",
  "目前只有 {} 一筆:{}。": "Only one record so far ({}): {}.",
  "記下各帳戶今天的餘額,這裡就會開始畫出你的淨資產。": "Record today's balance for each account and your net worth starts drawing here.",
  "自訂": "Custom",
  "從": "From",
  "到": "To",
  "這段期間的紀錄不到兩筆,畫不出趨勢。": "Fewer than two records in this range, so there's no trend to draw.",
}
